### ISSUE TITLE
Can't enter the code from that page

### ISSUE THREAD

**Issue by K4nape** [d0whc3r/node-gdrive#212]
Then i run this:
```
docker run --rm -v $PWD/secrets:/app/secrets:ro gdrive -l
```
Problem is
![image](https://user-images.githubusercontent.com/10292911/75239932-31487b00-57cc-11ea-96ea-93e2c48e816f.png)

I can't enter the code... whats the solution?

**Comment by d0whc3r** [comment]
Maybe you missed the first step https://github.com/d0whc3r/node-gdrive#key-create-credentials-and-token-files
You need to download credentials.json from google page and you need to be logged with google account that you what to use

**Comment by K4nape** [comment]
> Maybe you missed the first step https://github.com/d0whc3r/node-gdrive#key-create-credentials-and-token-files
> You need to download credentials.json from google page and you need to be logged with google account that you what to use

Yee, i know bro. I did it, but if i want try enter the code, you see in picture, i can't :( .
I feel something push enter 🌝

**Comment by d0whc3r** [comment]
then, you need to enable interactive terminal in docker
`docker run --rm -it -v $PWD/secrets:/app/secrets:rw d0whc3r/gdrive -l`
