### ISSUE TITLE
Failure when trying to show help from CLI

### ISSUE THREAD

**Issue by ajmas** [d0whc3r/node-gdrive#306]
**Describe the bug**

I installed node `@d0whc3r/node-gdrive` locally and then the following results in an error whereby minified code is displayed followed by an error `SyntaxError: Unexpected token '.'`:

```
 node_modules/.bin/node-gdrive --help        
```

Stack trace:

```js
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**To Reproduce**
1. `npm install @d0whc3r/node-gdrive`
2. `node_modules/.bin/node-gdrive --help`

**Expected behavior**

Expected to have CLI help displayed

**Screenshots**

<img width="1224" alt="Screenshot 2020-07-10 at 15 46 22" src="https://user-images.githubusercontent.com/682269/87192480-90fb7a80-c2c4-11ea-978e-f4a57ed0cfc8.png">

**Additional context**

Node: v12.16.2
Version: 3.4.0
OS: macOS 10.15.5

**Comment by d0whc3r** [comment]
Thanks to report, I will check asap

**Comment by d0whc3r** [comment]
I used node 14 and it works

- `yarn init -y && yarn add @d0whc3r/node-gdrive && ./node_modules/.bin/node-gdrive --help` - Working
- `npm init -y && npm install @d0whc3r/node-gdrive && ./node_modules/.bin/node-gdrive --help` - Working
- `npx @d0whc3r/node-gdrive --help` - Working

Then I used node 12.16.2 and it doesn't work

I will update build process to build with es2015
